name = "obsidianmcp"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
# Ces variables peuvent être définies dans Cloudflare ou GitHub Actions
STORJ_S3_ENDPOINT = "https://gateway.storjshare.io"

[observability]
[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true

